# Generated by Django 4.2.1 on 2023-06-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_avatar_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='image',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='https://w0.peakpx.com/wallpaper/416/975/HD-wallpaper-slowpoke-pokemon-face-eyes.jpg', max_length=250),
        ),
    ]
